### ISSUE TITLE
Requestions gif-autoplay, adapting grid view style; show videos as thumbnails

### ISSUE THREAD

**Issue by gitlerat** [Cyclenerd/gallery_shell#2]
Hi Nils,

great application! I was searching for something like this for days now :)

I want to change some of the code to view the images like this style: https://masonry.desandro.com/

Also I want to change that the Video Files will be previewed with Thumbnails (like images) and that the gifs autoplay in the overview section.

So why i am telling you this and not changing it by myself. I am a relativly newbie to this topic. 
Can you give me some hints where to start right with these changes? :)

kind regards!

**Comment by Cyclenerd** [comment]
You should make yourself familiar with [FFmpeg](http://ffmpeg.org/download.html). With `ffmpeg` you can export images from a video and make an animated gif.

Source:
https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video

With convert you can also create animated gifs:

```
convert -delay 100 -loop 0 *.png animation.gif
```
