### ISSUE TITLE
Video Version is Released (Static Video Gallery Generator Bash)

### ISSUE THREAD

**Issue by rojenzaman** [Cyclenerd/gallery_shell#3]
visit this repo for source: 
[https://github.com/rojenzaman/video-gallery-generator_bash](https://github.com/rojenzaman/video-gallery-generator_bash)

Demo Web Site:
[https://rojenzaman.github.io/video-gallery/](https://rojenzaman.github.io/video-gallery//)

adapted from [gallery_shell](https://github.com/Cyclenerd/gallery_shell/issues/3) project

**Comment by Cyclenerd** [comment]
thank you for this info
