### ISSUE TITLE
Atom Image Feed?

### ISSUE THREAD

**Issue by mro** [Cyclenerd/gallery_shell#4]
Hi Nils,

have you considered photo feeds like https://git.sr.ht/~mro/Photos2Atom to separate image preparation and viewing UX? The latter is bothering me quite a bit and I want subscribeable galleries.

Cheers, Marcus

**Comment by Cyclenerd** [comment]
Hi Marcus,

no I have not yet thought about it. Did not even know that RSS is still a thing and with photos I would not have expected it.

Best regards
Nils

**Comment by mro** [comment]
Hi Nils,

Atom is pretty much sleeping a sleeping beauty sleep – but it's like that ever since. So it's maybe no less than 2010 in absolute numbers – while the percentage is homeopathic, indeed.

But that aside - having javascript-less templating in the browser is nice in it's own terms, because raw data is immutable, re-styleable, reusable, subscribe able with pod catchers like e.g. https://miniflux.app/. Security is also great as well as longevity. I do it for a decade now for various purposes like image galleries https://darknet.mro.name/galleries/demo/ or microblogging https://demo.mro.name/shaarligo, API endpoints https://mro.name/g/u28br or radio broadcasts http://rec.mro.name/stations/b2/now. None of which sends html from the server to the client nor rely on Javascript in the client.

The one downside I know of, however, Google doesn't index it. Stupid, but true afaik. And xslt is really awkward, but does a great job.

Give Atom a thought, Yours,
Marcus
