### ISSUE TITLE
index.html layout is affected by different image sizes

### ISSUE THREAD

**Issue by RobOo-Github** [Cyclenerd/gallery_shell#6]
![Screenshot_2023-02-15_15-36-15](https://user-images.githubusercontent.com/65445647/219057837-e8fc4dde-b284-4bd4-aa15-ae4f7b73fe07.png)

Hi! 
I have images in 3:2 and 16:9 proportions in one directory. After running the gallery_shell script, I have an irregular looking layout in index.html, with images (almost?) overlapping.
I do not have the skill to fix this. Can you?
Thanks.

**Comment by Cyclenerd** [comment]
Hi,

Thank you for reporting this. I have fixed it. Only three images per row are now displayed.

![image](https://user-images.githubusercontent.com/176242/219958663-3b88fa06-2745-4dbe-8bcb-6c99aacf75e7.png)

Best regards
Nils
