### ISSUE TITLE
How to make it always display 3 columns?

### ISSUE THREAD

**Issue by tsxv478** [Cyclenerd/gallery_shell#7]
I'm not very good with css. What I want is to always have 3 column layout regardless of screen size (including on mobile) instead of cutting columns on smaller screens, and adjust the displayed image size so it fits well. Have no idea how to do this with this bootstrapped css.

**Comment by Cyclenerd** [comment]
Edit or remove the `row-cols-*`. More help: https://getbootstrap.com/docs/5.3/layout/gutters/#row-columns-gutters
